#%RAML 1.0
title: kuru
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/5ad35dbd-d3b6-4be7-baa7-020a862189de/ # baseUri: http://localhost:8081
/kuru:
  get:
    queryParameters:
      from:
      to:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "OLA Bike": "Bike No 1897",
                "Driver": "Kuru King of Sarrornagar",
                "Note ": "High Risk and Highly Expensive Under emergency situation definitely available "
              }
          
         
